/**
 * THIS FILE IS AUTO-GENERATED BY scripts/generate-env.js
 * DO NOT EDIT MANUALLY.
 * - En desarrollo local: edita .env.development
 * - En Netlify: define las variables de entorno en el panel de Netlify
 */
export const ENV = {
  production: false,
  apiUrl: '/api/v1',
  locationId: '550e8400-e29b-41d4-a716-446655440000'
};
