/**
 * THIS FILE IS AUTO-GENERATED BY scripts/generate-env.js
 * DO NOT EDIT MANUALLY. Update .env.development at repository root.
 */
export const ENV = {
  production: false,
  apiUrl: '/api/v1',
  locationId: '550e8400-e29b-41d4-a716-446655440000'
};
