const fs = require('fs');
const path = require('path');

function generateEnvFile(envFilePath, outputFilePath) {
  let fileEnvVars = {};

  // Intentar leer el archivo .env de respaldo (para desarrollo local)
  try {
    const envContent = fs.readFileSync(path.resolve(__dirname, '..', envFilePath), 'utf8');
    fileEnvVars = envContent.split('\n').reduce((acc, line) => {
      const match = line.match(/^([^=]+)=(.*)$/);
      if (match) {
        acc[match[1].trim()] = match[2].trim();
      }
      return acc;
    }, {});
  } catch (err) {
    console.warn(`Warning: Could not read ${envFilePath}. Using environment variables only.`);
  }

  // Las variables de entorno de process.env (Netlify) tienen PRIORIDAD sobre el archivo .env
  const apiUrl       = process.env.API_URL       || fileEnvVars.API_URL       || '/api/v1';
  const locationId   = process.env.LOCATION_ID   || fileEnvVars.LOCATION_ID   || '';
  const isProduction = process.env.NODE_ENV === 'production' || process.env.NETLIFY === 'true';

  const fileContent = `/**
 * THIS FILE IS AUTO-GENERATED BY scripts/generate-env.js
 * DO NOT EDIT MANUALLY.
 * - En desarrollo local: edita .env.development
 * - En Netlify: define las variables de entorno en el panel de Netlify
 */
export const ENV = {
  production: ${isProduction},
  apiUrl: '${apiUrl}',
  locationId: '${locationId}'
};
`;

  const dir = path.dirname(outputFilePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(outputFilePath, fileContent, 'utf8');
  console.log(`Generated ${outputFilePath} [apiUrl=${apiUrl}, locationId=${locationId}]`);
}

const outputPath = path.resolve(__dirname, '../src/app/core/config/env.config.ts');

// Generar config desde variables de entorno (Netlify) o desde .env.development (local)
generateEnvFile('.env.development', outputPath);
